# Generated by Django 6.0 on 2026-01-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.CharField(choices=[('SCI', 'Science'), ('INFO', 'Informative'), ('FACT', 'Fact'), ('TECH', 'Tech')], max_length=10, null=True),
        ),
    ]
