# Generated by Django 6.0 on 2026-01-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_topic_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tag',
            field=models.CharField(choices=[('Science', 'Science'), ('Informative', 'Informative'), ('Fact', 'Fact'), ('Tech', 'Tech')], max_length=120, null=True),
        ),
    ]
