# Generated by Django 6.0 on 2026-01-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_alter_topic_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='tag',
        ),
    ]
